package pac

import (
	"encoding/json"
	"fmt"
	"net"
	"strconv"
	"strings"

	managerconfig "github.com/openwrt-singbox/singbox-manager/internal/config"
)

type compiledRule struct {
	Pattern string `json:"pattern"`
	Action  string `json:"action"`
}

func Render(cfg managerconfig.Config) ([]byte, error) {
	return RenderForProxyHost(cfg, "")
}

func RenderForProxyHost(cfg managerconfig.Config, proxyHost string) ([]byte, error) {
	proxy := proxyDirective(cfg, proxyHost)
	direct := "DIRECT"
	rules := compileRules(cfg.PAC)

	ruleData, err := json.Marshal(rules)
	if err != nil {
		return nil, err
	}
	proxyData, err := json.Marshal(proxy)
	if err != nil {
		return nil, err
	}
	directData, err := json.Marshal(direct)
	if err != nil {
		return nil, err
	}

	localBypass := "false"
	if cfg.PAC.LocalBypass {
		localBypass = "true"
	}

	body := fmt.Sprintf(`// Generated by singbox-manager.
var SINGBOX_MANAGER_PROXY = %s;
var SINGBOX_MANAGER_DIRECT = %s;
var SINGBOX_MANAGER_LOCAL_BYPASS = %s;
var SINGBOX_MANAGER_RULES = %s;

function normalizeHost(host) {
  return (host || "").toLowerCase().replace(/\.$/, "");
}

function isLocalHost(host) {
  if (isPlainHostName(host) || host === "localhost")
    return true;
  if (shExpMatch(host, "127.*") || shExpMatch(host, "10.*") || shExpMatch(host, "192.168.*"))
    return true;
  if (shExpMatch(host, "172.16.*") || shExpMatch(host, "172.17.*") || shExpMatch(host, "172.18.*") || shExpMatch(host, "172.19.*"))
    return true;
  if (shExpMatch(host, "172.2?.*") || shExpMatch(host, "172.30.*") || shExpMatch(host, "172.31.*"))
    return true;
  if (shExpMatch(host, "169.254.*") || host === "::1")
    return true;
  return false;
}

function domainMatch(host, pattern) {
  pattern = normalizeHost(pattern);
  if (!pattern)
    return false;
  if (pattern.charAt(0) === ".")
    return dnsDomainIs(host, pattern);
  if (pattern.indexOf("*") >= 0)
    return shExpMatch(host, pattern);
  return host === pattern || dnsDomainIs(host, "." + pattern);
}

function FindProxyForURL(url, host) {
  host = normalizeHost(host);
  if (SINGBOX_MANAGER_LOCAL_BYPASS && isLocalHost(host))
    return SINGBOX_MANAGER_DIRECT;
  for (var i = 0; i < SINGBOX_MANAGER_RULES.length; i++) {
    var rule = SINGBOX_MANAGER_RULES[i];
    if (domainMatch(host, rule.pattern))
      return rule.action === "direct" ? SINGBOX_MANAGER_DIRECT : SINGBOX_MANAGER_PROXY;
  }
  return SINGBOX_MANAGER_PROXY;
}
`, proxyData, directData, localBypass, ruleData)
	return []byte(body), nil
}

func RenderActive(cfg managerconfig.Config) ([]byte, error) {
	return RenderActiveForProxyHost(cfg, "")
}

func RenderActiveForProxyHost(cfg managerconfig.Config, proxyHost string) ([]byte, error) {
	if cfg.PAC.Source == "custom" {
		custom, ok := cfg.CustomPACs[cfg.PAC.SelectedCustom]
		if !ok {
			return nil, fmt.Errorf("custom PAC %q not found", cfg.PAC.SelectedCustom)
		}
		if !custom.Enabled {
			return nil, fmt.Errorf("custom PAC %q is disabled", cfg.PAC.SelectedCustom)
		}
		return []byte(custom.Content), nil
	}
	return RenderForProxyHost(cfg, proxyHost)
}

func compileRules(pac managerconfig.PAC) []compiledRule {
	rules := []compiledRule{}
	for _, raw := range pac.CustomRules {
		pattern, action := parseRule(raw)
		if pattern != "" {
			rules = append(rules, compiledRule{Pattern: pattern, Action: action})
		}
	}
	for _, pattern := range pac.Whitelist {
		pattern = strings.TrimSpace(pattern)
		if pattern != "" {
			rules = append(rules, compiledRule{Pattern: pattern, Action: "direct"})
		}
	}
	for _, pattern := range pac.Blacklist {
		pattern = strings.TrimSpace(pattern)
		if pattern != "" {
			rules = append(rules, compiledRule{Pattern: pattern, Action: "proxy"})
		}
	}
	return rules
}

func parseRule(raw string) (string, string) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "", "proxy"
	}
	if strings.Contains(raw, ",") {
		parts := strings.SplitN(raw, ",", 2)
		return strings.TrimSpace(parts[0]), normalizeAction(parts[1])
	}
	fields := strings.Fields(raw)
	if len(fields) == 1 {
		return fields[0], "proxy"
	}
	if isAction(fields[0]) {
		return strings.Join(fields[1:], " "), normalizeAction(fields[0])
	}
	return fields[0], normalizeAction(fields[1])
}

func normalizeAction(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	switch value {
	case "direct":
		return "direct"
	default:
		return "proxy"
	}
}

func isAction(value string) bool {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "direct", "proxy", "block", "reject":
		return true
	default:
		return false
	}
}

func proxyDirective(cfg managerconfig.Config, proxyHost string) string {
	host := strings.TrimSpace(cfg.Manager.MixedListen)
	if isUnspecifiedHost(host) {
		host = hostOnly(proxyHost)
		if host == "" {
			host = "127.0.0.1"
		}
	}
	if strings.Contains(host, ":") && !strings.HasPrefix(host, "[") {
		host = "[" + host + "]"
	}
	return "PROXY " + host + ":" + strconv.Itoa(cfg.Manager.MixedPort) + "; DIRECT"
}

func isUnspecifiedHost(host string) bool {
	host = strings.Trim(strings.TrimSpace(host), "[]")
	if host == "" {
		return true
	}
	if parsed := net.ParseIP(host); parsed != nil {
		return parsed.IsUnspecified()
	}
	return false
}

func hostOnly(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}
	if host, _, err := net.SplitHostPort(value); err == nil {
		return usableHost(host)
	}
	if strings.HasPrefix(value, "[") {
		end := strings.Index(value, "]")
		if end > 0 {
			return usableHost(value[1:end])
		}
	}
	if strings.Count(value, ":") == 1 {
		host, _, _ := strings.Cut(value, ":")
		return usableHost(host)
	}
	return usableHost(value)
}

func usableHost(host string) string {
	host = strings.Trim(strings.TrimSpace(host), "[]")
	if host == "" {
		return ""
	}
	if parsed := net.ParseIP(host); parsed != nil && parsed.IsUnspecified() {
		return ""
	}
	return host
}
