package firewall

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	managerconfig "github.com/openwrt-singbox/singbox-manager/internal/config"
)

const (
	DefaultIncludePath = "/etc/nftables.d/90-singbox-manager.nft"
	tproxyMark         = "0x1"
)

func Render(cfg managerconfig.Config) ([]byte, error) {
	if !cfg.TProxy.Enabled {
		return nil, nil
	}
	if len(cfg.TProxy.LANIfnames) == 0 {
		return nil, fmt.Errorf("tproxy.main.lan_ifname is required when tproxy is enabled")
	}

	ipv4Exclude, ipv6Exclude := splitSubnets(cfg.TProxy.ExcludeSubnet)
	ipv4Include, ipv6Include := splitSubnets(cfg.TProxy.IncludeSubnet)

	var builder strings.Builder
	builder.WriteString("# Generated by singbox-manager. Do not edit.\n")
	builder.WriteString("# This fragment is loaded by OpenWrt firewall4 from /etc/nftables.d/.\n\n")
	builder.WriteString("chain singbox_manager_tproxy_prerouting {\n")
	builder.WriteString("\ttype filter hook prerouting priority mangle; policy accept;\n")
	builder.WriteString("\tiifname != ")
	builder.WriteString(nftStringSet(cfg.TProxy.LANIfnames))
	builder.WriteString(" return\n")
	if len(cfg.TProxy.IncludeMAC) > 0 {
		builder.WriteString("\tether saddr != ")
		builder.WriteString(nftRawSet(cfg.TProxy.IncludeMAC))
		builder.WriteString(" return\n")
	}
	if len(cfg.TProxy.IncludeSubnet) > 0 {
		if len(ipv4Include) > 0 {
			builder.WriteString("\tmeta nfproto ipv4 ip daddr != ")
			builder.WriteString(nftRawSet(ipv4Include))
			builder.WriteString(" return\n")
		} else {
			builder.WriteString("\tmeta nfproto ipv4 return\n")
		}
		if len(ipv6Include) > 0 {
			builder.WriteString("\tmeta nfproto ipv6 ip6 daddr != ")
			builder.WriteString(nftRawSet(ipv6Include))
			builder.WriteString(" return\n")
		} else {
			builder.WriteString("\tmeta nfproto ipv6 return\n")
		}
	}
	if cfg.TProxy.DNSHijack {
		builder.WriteString("\tudp dport 53 redirect to :")
		builder.WriteString(fmt.Sprint(cfg.Manager.DNSPort))
		builder.WriteString("\n")
		builder.WriteString("\ttcp dport 53 redirect to :")
		builder.WriteString(fmt.Sprint(cfg.Manager.DNSPort))
		builder.WriteString("\n")
	}
	builder.WriteString("\tfib daddr type { local, broadcast, multicast } return\n")
	if len(ipv4Exclude) > 0 {
		builder.WriteString("\tmeta nfproto ipv4 ip daddr ")
		builder.WriteString(nftRawSet(ipv4Exclude))
		builder.WriteString(" return\n")
	}
	if len(ipv6Exclude) > 0 {
		builder.WriteString("\tmeta nfproto ipv6 ip6 daddr ")
		builder.WriteString(nftRawSet(ipv6Exclude))
		builder.WriteString(" return\n")
	}
	builder.WriteString("\tmeta l4proto { tcp, udp } meta mark set ")
	builder.WriteString(tproxyMark)
	builder.WriteString(" tproxy to :")
	builder.WriteString(fmt.Sprint(cfg.Manager.TProxyPort))
	builder.WriteString(" accept\n")
	builder.WriteString("}\n")

	return []byte(builder.String()), nil
}

func Apply(cfg managerconfig.Config, path string) error {
	if path == "" {
		path = DefaultIncludePath
	}
	if !cfg.TProxy.Enabled {
		return Cleanup(path)
	}
	data, err := Render(cfg)
	if err != nil {
		return err
	}
	return writeFileAtomic(path, data, 0644)
}

func Cleanup(path string) error {
	if path == "" {
		path = DefaultIncludePath
	}
	err := os.Remove(path)
	if err == nil || os.IsNotExist(err) {
		return nil
	}
	return err
}

func splitSubnets(values []string) ([]string, []string) {
	ipv4 := []string{}
	ipv6 := []string{}
	for _, value := range values {
		if strings.Contains(value, ":") {
			ipv6 = append(ipv6, value)
		} else {
			ipv4 = append(ipv4, value)
		}
	}
	sort.Strings(ipv4)
	sort.Strings(ipv6)
	return ipv4, ipv6
}

func nftStringSet(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, `"`+strings.ReplaceAll(value, `"`, `\"`)+`"`)
	}
	sort.Strings(quoted)
	return nftRawSet(quoted)
}

func nftRawSet(values []string) string {
	return "{ " + strings.Join(values, ", ") + " }"
}

func writeFileAtomic(path string, data []byte, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer func() {
		_ = os.Remove(tmpPath)
	}()

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(mode); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpPath, path)
}
