package firewall

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	managerconfig "github.com/openwrt-singbox/singbox-manager/internal/config"
)

const (
	DefaultIncludePath = "/etc/nftables.d/90-singbox-manager.nft"
	tproxyMark         = "0x1"

	reservedV4 = "{ 127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 169.254.0.0/16, 100.64.0.0/10 }"
	reservedV6 = "{ fc00::/7, fe80::/10 }"
)

// Named-set identifiers. Device traffic is gated through these so the manager
// can later toggle a single device with `nft add/delete element` without
// re-rendering, and so include/exclude semantics live in one place.
const (
	setTProxyMAC    = "singbox_manager_tproxy_mac"
	setTProxy4      = "singbox_manager_tproxy4"
	setTProxy6      = "singbox_manager_tproxy6"
	setBypassMAC    = "singbox_manager_bypass_mac"
	setBypass4      = "singbox_manager_bypass4"
	setBypass6      = "singbox_manager_bypass6"
	setUDPBypassMAC = "singbox_manager_udpbypass_mac"
	setUDPBypass4   = "singbox_manager_udpbypass4"
	setUDPBypass6   = "singbox_manager_udpbypass6"
	setBypassDst4   = "singbox_manager_bdst4"
	setBypassDst6   = "singbox_manager_bdst6"

	tproxyDo = "singbox_manager_tproxy_do"
)

// FW4Table is the nftables table OpenWrt firewall4 loads the manager's include
// fragment into. Named sets below live here.
const FW4Table = "inet fw4"

// ManagedSets are the named sets the manager owns inside FW4Table. They must be
// flushed before every `fw4 reload`: that reload runs `flush table inet fw4`,
// which clears chain rules but NOT named-set elements, and the re-included
// fragment only *merges* elements. Without an explicit flush, stale per-device
// elements survive a reload (a device left in both the tproxy and bypass sets),
// so device-override changes never take effect until a full `fw4 restart`.
var ManagedSets = []string{
	setTProxyMAC, setTProxy4, setTProxy6,
	setBypassMAC, setBypass4, setBypass6,
	setUDPBypassMAC, setUDPBypass4, setUDPBypass6,
	setBypassDst4, setBypassDst6,
}

// buckets holds the per-mode device address sets. A device resolves to exactly
// one effective mode, so its source addresses land in exactly one of the
// tproxy/bypass buckets. The udpbypass bucket overlaps the tproxy bucket: a
// tproxy device with BypassUDP set appears in both so its TCP is still tproxied
// while its UDP egresses directly.
type buckets struct {
	tproxyMAC, tproxy4, tproxy6          []string
	bypassMAC, bypass4, bypass6          []string
	udpBypassMAC, udpBypass4, udpBypass6 []string
}

func bucketDevices(cfg managerconfig.Config) buckets {
	devices := append([]managerconfig.Device(nil), cfg.Transparent.Devices...)
	sort.Slice(devices, func(i, j int) bool { return devices[i].ID < devices[j].ID })

	var b buckets
	for _, device := range devices {
		if !device.Enabled {
			continue
		}
		var mac, v4, v6 *[]string
		switch cfg.Transparent.Effective(device) {
		case "tproxy":
			mac, v4, v6 = &b.tproxyMAC, &b.tproxy4, &b.tproxy6
		case "bypass":
			mac, v4, v6 = &b.bypassMAC, &b.bypass4, &b.bypass6
		default:
			continue // "off" — not proxied, not bypassed
		}
		appendDevice(mac, v4, v6, device)
		if device.BypassUDP && cfg.Transparent.Effective(device) == "tproxy" {
			appendDevice(&b.udpBypassMAC, &b.udpBypass4, &b.udpBypass6, device)
		}
	}
	return b
}

func appendDevice(mac, v4, v6 *[]string, device managerconfig.Device) {
	if device.MAC != "" {
		*mac = append(*mac, strings.ToLower(device.MAC))
	}
	if device.IPv4 != "" {
		*v4 = append(*v4, device.IPv4)
	}
	if device.IPv6 != "" {
		*v6 = append(*v6, device.IPv6)
	}
}

func Render(cfg managerconfig.Config) ([]byte, error) {
	if !cfg.Transparent.Active() {
		return nil, nil
	}
	if len(cfg.Transparent.LANIfnames) == 0 {
		return nil, fmt.Errorf("transparent.main.lan_ifname is required when proxying is enabled")
	}

	b := bucketDevices(cfg)
	ipv4Bypass, ipv6Bypass := splitSubnets(cfg.Transparent.BypassSubnet)

	var builder strings.Builder
	builder.WriteString("# Generated by singbox-manager. Do not edit.\n")
	builder.WriteString("# This fragment is loaded by OpenWrt firewall4 from /etc/nftables.d/.\n\n")
	writeSets(&builder, b, ipv4Bypass, ipv6Bypass)

	if cfg.UsesTProxy() {
		builder.WriteString("\n")
		writeTProxyChain(&builder, cfg, cfg.Transparent.DefaultMode == "tproxy")
	}
	if cfg.Transparent.KillSwitch {
		builder.WriteString("\n")
		writeKillSwitchForwardChain(&builder, cfg)
	}

	return []byte(builder.String()), nil
}

func RenderKillSwitch(cfg managerconfig.Config) ([]byte, error) {
	if !cfg.Transparent.Active() || !cfg.Transparent.KillSwitch {
		return nil, nil
	}
	if len(cfg.Transparent.LANIfnames) == 0 {
		return nil, fmt.Errorf("transparent.main.lan_ifname is required when proxying is enabled")
	}

	b := bucketDevices(cfg)
	ipv4Bypass, ipv6Bypass := splitSubnets(cfg.Transparent.BypassSubnet)

	var builder strings.Builder
	builder.WriteString("# Generated by singbox-manager. Do not edit.\n")
	builder.WriteString("# Transparent-proxy kill switch is active; routed traffic in scope is blocked.\n\n")
	writeSets(&builder, b, ipv4Bypass, ipv6Bypass)
	builder.WriteString("\n")
	writeKillSwitchForwardChain(&builder, cfg)
	return []byte(builder.String()), nil
}

func writeSets(builder *strings.Builder, b buckets, ipv4Bypass []string, ipv6Bypass []string) {
	writeMACSet(builder, setTProxyMAC, b.tproxyMAC)
	writeAddrSet(builder, setTProxy4, "ipv4_addr", b.tproxy4)
	writeAddrSet(builder, setTProxy6, "ipv6_addr", b.tproxy6)
	writeMACSet(builder, setBypassMAC, b.bypassMAC)
	writeAddrSet(builder, setBypass4, "ipv4_addr", b.bypass4)
	writeAddrSet(builder, setBypass6, "ipv6_addr", b.bypass6)
	writeMACSet(builder, setUDPBypassMAC, b.udpBypassMAC)
	writeAddrSet(builder, setUDPBypass4, "ipv4_addr", b.udpBypass4)
	writeAddrSet(builder, setUDPBypass6, "ipv6_addr", b.udpBypass6)
	writeAddrSet(builder, setBypassDst4, "ipv4_addr", ipv4Bypass)
	writeAddrSet(builder, setBypassDst6, "ipv6_addr", ipv6Bypass)
}

func writeMACSet(builder *strings.Builder, name string, values []string) {
	fmt.Fprintf(builder, "set %s {\n\ttype ether_addr\n", name)
	writeSetElements(builder, values)
	builder.WriteString("}\n")
}

func writeAddrSet(builder *strings.Builder, name string, typ string, values []string) {
	fmt.Fprintf(builder, "set %s {\n\ttype %s\n\tflags interval\n", name, typ)
	writeSetElements(builder, values)
	builder.WriteString("}\n")
}

func writeSetElements(builder *strings.Builder, values []string) {
	if len(values) == 0 {
		return
	}
	sorted := append([]string(nil), values...)
	sort.Strings(sorted)
	builder.WriteString("\telements = { ")
	builder.WriteString(strings.Join(sorted, ", "))
	builder.WriteString(" }\n")
}

// writeTProxyChain renders the mangle-table TCP+UDP tproxy path. DNS is handled
// by sing-box's hijack-dns route rule, so this chain emits no nat statement and
// therefore loads cleanly in a filter/mangle chain.
//
// Ordering matters. In catch-all mode the full-device bypass carve-outs run
// first so a fully-bypassed device is direct for everything, DNS included. Then,
// crucially, DNS is captured *before* the UDP-bypass and local/reserved returns:
// a UDP-bypass device (proxied TCP, direct UDP) must still have its DNS — which
// is UDP/53 — hijacked, or its resolution leaks direct and sing-box can't route
// it. LAN clients also normally resolve through the router itself — a local,
// private address — so without an early port-53 tproxy their DNS would be
// returned by the local/reserved rules and never reach sing-box. Only after DNS
// is captured do the remaining per-device UDP opt-outs and router-local/private
// destinations bypass as before.
func writeTProxyChain(builder *strings.Builder, cfg managerconfig.Config, catchAll bool) {
	builder.WriteString("chain singbox_manager_tproxy {\n")
	builder.WriteString("\ttype filter hook prerouting priority mangle; policy accept;\n")
	fmt.Fprintf(builder, "\tiifname != %s return\n", nftStringSet(cfg.Transparent.LANIfnames))
	builder.WriteString("\tfib daddr type { broadcast, multicast } return\n")

	if catchAll {
		writeCarveOuts(builder, setBypassMAC, setBypass4, setBypass6)
	}

	// Destinations the user pins as direct egress directly — DNS included.
	fmt.Fprintf(builder, "\tip daddr @%s return\n", setBypassDst4)
	fmt.Fprintf(builder, "\tip6 daddr @%s return\n", setBypassDst6)

	// Capture in-scope DNS before the UDP-bypass and local/reserved returns so
	// queries aimed at the router (the default LAN resolver) are tproxied and
	// hijacked too — even for devices whose other UDP egresses directly.
	if cfg.Transparent.DNSHijack {
		if catchAll {
			fmt.Fprintf(builder, "\tmeta l4proto { tcp, udp } th dport 53 goto %s\n", tproxyDo)
		} else {
			writeDNSGotos(builder, tproxyDo, setTProxyMAC, setTProxy4, setTProxy6)
		}
	}

	// UDP that opted out of proxying (gaming consoles etc.) egresses directly.
	// This runs after DNS capture so port-53 UDP is still hijacked.
	writeUDPBypass(builder)

	// Non-DNS traffic to the router itself or to private/reserved ranges is not
	// proxied.
	builder.WriteString("\tfib daddr type local return\n")
	fmt.Fprintf(builder, "\tip daddr %s return\n", reservedV4)
	fmt.Fprintf(builder, "\tip6 daddr %s return\n", reservedV6)

	if catchAll {
		fmt.Fprintf(builder, "\tgoto %s\n", tproxyDo)
	} else {
		writeGotos(builder, tproxyDo, setTProxyMAC, setTProxy4, setTProxy6)
	}
	builder.WriteString("}\n")

	fmt.Fprintf(builder, "chain %s {\n", tproxyDo)
	fmt.Fprintf(builder, "\tmeta l4proto { tcp, udp } meta mark set %s tproxy to :%d accept\n", tproxyMark, cfg.Manager.TProxyPort)
	builder.WriteString("}\n")
}

// writeUDPBypass returns UDP traffic sourced from devices that opted out of
// proxied UDP (gaming consoles etc.) so it egresses directly.
func writeUDPBypass(builder *strings.Builder) {
	fmt.Fprintf(builder, "\tmeta l4proto udp ether saddr @%s return\n", setUDPBypassMAC)
	fmt.Fprintf(builder, "\tmeta l4proto udp ip saddr @%s return\n", setUDPBypass4)
	fmt.Fprintf(builder, "\tmeta l4proto udp ip6 saddr @%s return\n", setUDPBypass6)
}

func writeKillSwitchForwardChain(builder *strings.Builder, cfg managerconfig.Config) {
	builder.WriteString("chain singbox_manager_kill_switch_forward {\n")
	builder.WriteString("\ttype filter hook forward priority filter; policy accept;\n")
	writeScopeFilters(builder, cfg)
	// UDP-bypass devices egress UDP directly by design, so the kill switch must
	// let it through even while routing is down — otherwise it is dropped here.
	writeUDPBypass(builder)
	if cfg.Transparent.DefaultMode == "off" {
		// Whitelist: only explicitly pinned devices are in scope.
		writeDrops(builder, setTProxyMAC, setTProxy4, setTProxy6)
	} else {
		writeCarveOuts(builder, setBypassMAC, setBypass4, setBypass6)
		builder.WriteString("\tcounter drop\n")
	}
	builder.WriteString("}\n")
}

func writeScopeFilters(builder *strings.Builder, cfg managerconfig.Config) {
	fmt.Fprintf(builder, "\tiifname != %s return\n", nftStringSet(cfg.Transparent.LANIfnames))
	builder.WriteString("\tfib daddr type { local, broadcast, multicast } return\n")
	fmt.Fprintf(builder, "\tip daddr %s return\n", reservedV4)
	fmt.Fprintf(builder, "\tip6 daddr %s return\n", reservedV6)
	fmt.Fprintf(builder, "\tip daddr @%s return\n", setBypassDst4)
	fmt.Fprintf(builder, "\tip6 daddr @%s return\n", setBypassDst6)
}

func writeCarveOuts(builder *strings.Builder, macSet string, v4Set string, v6Set string) {
	fmt.Fprintf(builder, "\tether saddr @%s return\n", macSet)
	fmt.Fprintf(builder, "\tip saddr @%s return\n", v4Set)
	fmt.Fprintf(builder, "\tip6 saddr @%s return\n", v6Set)
}

func writeGotos(builder *strings.Builder, target string, macSet string, v4Set string, v6Set string) {
	fmt.Fprintf(builder, "\tether saddr @%s goto %s\n", macSet, target)
	fmt.Fprintf(builder, "\tip saddr @%s goto %s\n", v4Set, target)
	fmt.Fprintf(builder, "\tip6 saddr @%s goto %s\n", v6Set, target)
}

// writeDNSGotos sends in-scope devices' DNS (TCP+UDP port 53) to the tproxy
// target. It mirrors writeGotos but matches only port 53, so it can run before
// the local/reserved returns and still capture DNS aimed at the router.
func writeDNSGotos(builder *strings.Builder, target string, macSet string, v4Set string, v6Set string) {
	fmt.Fprintf(builder, "\tether saddr @%s meta l4proto { tcp, udp } th dport 53 goto %s\n", macSet, target)
	fmt.Fprintf(builder, "\tip saddr @%s meta l4proto { tcp, udp } th dport 53 goto %s\n", v4Set, target)
	fmt.Fprintf(builder, "\tip6 saddr @%s meta l4proto { tcp, udp } th dport 53 goto %s\n", v6Set, target)
}

func writeDrops(builder *strings.Builder, macSet string, v4Set string, v6Set string) {
	fmt.Fprintf(builder, "\tether saddr @%s counter drop\n", macSet)
	fmt.Fprintf(builder, "\tip saddr @%s counter drop\n", v4Set)
	fmt.Fprintf(builder, "\tip6 saddr @%s counter drop\n", v6Set)
}

func Apply(cfg managerconfig.Config, path string) error {
	if path == "" {
		path = DefaultIncludePath
	}
	if !cfg.Transparent.Active() {
		return Cleanup(path)
	}
	data, err := Render(cfg)
	if err != nil {
		return err
	}
	return writeFileAtomic(path, data, 0644)
}

func ApplyKillSwitch(cfg managerconfig.Config, path string) error {
	if path == "" {
		path = DefaultIncludePath
	}
	data, err := RenderKillSwitch(cfg)
	if err != nil {
		return err
	}
	if len(data) == 0 {
		return Cleanup(path)
	}
	return writeFileAtomic(path, data, 0644)
}

func Cleanup(path string) error {
	if path == "" {
		path = DefaultIncludePath
	}
	err := os.Remove(path)
	if err == nil || os.IsNotExist(err) {
		return nil
	}
	return err
}

func splitSubnets(values []string) ([]string, []string) {
	ipv4 := []string{}
	ipv6 := []string{}
	for _, value := range values {
		if strings.Contains(value, ":") {
			ipv6 = append(ipv6, value)
		} else {
			ipv4 = append(ipv4, value)
		}
	}
	sort.Strings(ipv4)
	sort.Strings(ipv6)
	return ipv4, ipv6
}

func nftStringSet(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, `"`+strings.ReplaceAll(value, `"`, `\"`)+`"`)
	}
	sort.Strings(quoted)
	return "{ " + strings.Join(quoted, ", ") + " }"
}

func writeFileAtomic(path string, data []byte, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer func() {
		_ = os.Remove(tmpPath)
	}()

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(mode); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpPath, path)
}
