#!/bin/sh

mkdir -p /etc/singbox-manager/generated
mkdir -p /etc/singbox-manager/rulesets
mkdir -p /var/run/singbox-manager
mkdir -p /var/run/sing-box

[ -x /etc/init.d/singbox-managerd ] && /etc/init.d/singbox-managerd enable

exit 0
