include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-singbox-manager
PKG_VERSION:=0.1.0
PKG_RELEASE:=2

LUCI_TITLE:=LuCI support for SingBox Manager
LUCI_DEPENDS:=+singbox-manager
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
